"""empty message

Revision ID: c5a6366de83c
Revises: bcac3be167e7
Create Date: 2020-08-21 20:59:31.445678

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c5a6366de83c'
down_revision = 'bcac3be167e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'photo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('photo', mysql.MEDIUMBLOB(), nullable=True))
    # ### end Alembic commands ###
